# Generated by Django 6.0.3 on 2026-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('icon', models.CharField(default='percent', help_text='Lucide icon name (e.g., percent, award, shopping-bag)', max_length=50)),
                ('color_hex', models.CharField(default='#3b82f6', help_text='Hex color for the brand (e.g., #3b82f6 for blue)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
